apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lib2uwqby-go 
  janus-idp.io/tekton: lib2uwqby-go
  backstage.io/kubernetes-id: lib2uwqby-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lib2uwqby-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml